### ISSUE TITLE
hevc_nvenc 压片报错驱动版本太低

### ISSUE THREAD

**Issue by SlackXiao** [rxaa/MediaMux#1]
-i "E:\OBS_Videos\2019.07.03.f4v" 

 -map 0:0 -codec:0 hevc_nvenc -qp:0 10  -r:0 12  
 -map 0:1 -codec:1  copy   -metadata:s:1 language="chi" 
 

 -strict -2 -y "E:\OBS_Videos\2019.07.03mmux.mkv" 
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'E:\OBS_Videos\2019.07.03.f4v':
  Metadata:
    major_brand     : f4v 
    minor_version   : 512
    compatible_brands: isomiso2avc1
    encoder         : Lavf57.48.101
  Duration: 00:47:02.53, start: 0.066000, bitrate: 5075 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x720, 5000 kb/s, 29.99 fps, 30 tbr, 90k tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 63 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> hevc (hevc_nvenc))
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[hevc_nvenc @ 0000028df6d60f00] Driver does not support the required nvenc API version. Required: 9.0 Found: 8.1
[hevc_nvenc @ 0000028df6d60f00] The minimum required Nvidia driver for nvenc is 390.77 or newer
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

**Comment by SlackXiao** [comment]
用的 MediaMux64  1.4.0，  N卡驱动417.71   win 10

**Comment by rxaa** [comment]
显卡是什么型号的？

**Comment by SlackXiao** [comment]
1080ti

**Comment by SlackXiao** [comment]
> 显卡是什么型号的？

1080ti

**Comment by rxaa** [comment]
ffmpeg4.1.1以上使用了9.0版本nvenc sdk。需要最新的419驱动。
所以新版回退到了ffmpeg4.1版本。

**Comment by SlackXiao** [comment]
> ffmpeg4.1.1以上使用了9.0版本nvenc sdk。需要最新的419驱动。
> 所以新版回退到了ffmpeg4.1版本。

nvenc 压片几分钟完事，换成cpu压片（i7 2600k）得几小时，建议加上暂停取消功能。
否则的手动去干掉ffmpeg进程取消压片

**Comment by rxaa** [comment]
> nvenc 压片几分钟完事，换成cpu压片（i7 2600k）得几小时，建议加上暂停取消功能。
> 否则的手动去干掉ffmpeg进程取消压片

菜单‘封装’里有个‘停止’功能，以后也可能会加上暂停/恢复功能。
