### ISSUE TITLE
建议更新下FFmpeg

### ISSUE THREAD

**Issue by StrollStars** [rxaa/MediaMux#9]
用最新版的FFmpeg替换内置的版本会报错，因为最新版没有FFmpegPlayer.dll文件，希望开发者能更新下。

**Comment by hirrao** [comment]
其实可以把这个文件留着，然后其他换成新版的，实测可行，就是ffmpeg转码时也不用这个文件

**Comment by StrollStars** [comment]
@snowways 不好意思没看懂，是指把FFmpeg留着，把MediaMux的其他文件更新吗？可MediaMux已经是目前的最新版了。

**Comment by hirrao** [comment]
> @snowways 不好意思没看懂，是指把FFmpeg留着，把MediaMux的其他文件更新吗？可MediaMux已经是目前的最新版了。

就是用目前的meidaMux，然后你下载新的ffmpeg的full build，然后直接把新的ffmpeg.exe替换掉MediaMux里面带的那个ffmpeg

**Comment by StrollStars** [comment]
@snowways 试了下确实可以，感谢分享。
